# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name:  'Azure Pipelines'

steps:
- script: |
    echo "âœ… Pipeline started"
    echo "Agent name      : $(Agent.Name)"
    echo "Agent pool      : $(Agent.PoolName)"
    echo "Machine name    : $(Agent.MachineName)"
    echo "OS              : $(Agent.OS)"
    echo "Workspace       : $(Build.SourcesDirectory)"
    echo "User            : $(whoami)"
    uname -a
  displayName: "Verify self-hosted agent"
